#!/bin/bash
docker run -d --restart unless-stopped \
-e "http.host=0.0.0.0" \
-e "transport.host=127.0.0.1" \
-e "ES_JAVA_OPTS=-Xms1g -Xmx2g" \
--name elasticsearch-v6 \
-p 9200:9200 \
-p 9300:9300 \
-v "`pwd`/data":/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
