#!/bin/bash

if [ "$1" == "" ] ; then
  echo "please provide a name for Elastic Search container to link to"
  echo "syntax: $0 [ES container]"
  exit 0
fi

if [ "$2" == "" ] ; then
  echo "please provide a absolute path where logs are stored"
  echo "syntax: $0 [Folder path]"
  exit 0
fi

docker run -d --name cloudtrail-2-elk \
-v `pwd`/import.py:/bin/import.py \
-v $2:/mnt/ \
--link $1:elasticsearch \
-d python:latest \
/bin/bash -c 'pip install elasticsearch ; /bin/import.py'
